### ISSUE TITLE
Method declaration on multiple lines

### ISSUE THREAD

**Issue by burgyl** [Skrealz/10-commandments#5]
If the method declaration is on multiple lines, the program doesn't get the method name entirely.

For example if I have this method declaration : 
```java
    public static op void bisection (double lLim, double uLim, double precision, cap double (double) f,
            cap void (double, double) callback) {
```
It will find ```void (double, double) callback)``` as the method name.

**Comment by phungthomas** [comment]
This is tragic. I can't believe this happens on this beautifully crafted piece of software. I will hire someone to deal with this issue as fast as possible.

**Comment by burgyl** [comment]
Thank you for your professionalism

**Comment by phungthomas** [comment]
Hello, I have found someone to work on this bug. It will be fixed very soon.
